# Site settings
name: EBI Adaptive Content Model
group: EMBL-EBI Web Development
email: khawkins@ebi.ac.uk
domain: //khawkins98.github.io
baseurl: /EBI-Adaptive-content-model
permalink: pretty

# Add custom CSS / JS here
# custom_css:
# - "{{site.baseurl}}/static/css/YOUR-CSS-COMPONENTS.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
# custom_js:
# - "{{site.baseurl}}/static/js/YOUR-CSS-COMPONENTS.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"
ga_code: 'UA-XXXXX-X'

# Build settings
markdown: kramdown
